build:
  maxIssues: 0

lumen-tokens:
  active: true
  ForbiddenScreenDpLiteral:
    active: true
  ForbiddenScreenColorLiteral:
    active: true
  ForbiddenScreenMaterialColors:
    active: true
  ForbiddenScreenRoundedCornerShape:
    active: true
